version: '3'
services:
  nginx:
    build: "./Infrastructure/nginx/"
    volumes:
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
    networks:
      naomo-network:
        ipv4_address: 172.23.0.4
  python:
    build: "./Infrastructure/python/"
    volumes:
      - ./Application/naomo:/home/work/naomo
      - ./logs/django:/home/work/django
      - ./logs/uwsgi:/home/work/uwsgi
    ports:
      - "8000:8000"
    networks:
      naomo-network:
        ipv4_address: 172.23.0.5
  mysql:
    build: "./Infrastructure/mysql/"
    volumes:
      - ./Infrastructure/mysql/init:/docker-entrypoint-initdb.d
      - ./logs/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=naomo
      - MYSQL_ROOT_PASSWORD=krzmknt
      - TZ="Asia/Tokyo"
    ports:
      - "3306:3306"
    networks:
      naomo-network:
        ipv4_address: 172.23.0.6
networks:
  naomo-network:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.23.0.0/24
